apiVersion: v2
name: projectsveltos
version: 1.0.0
description: This Chart deploys the Sveltos Project environment.
dependencies:
  - name: projectsveltos
    version: 1.3.1
    repository: https://projectsveltos.github.io/helm-charts
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
