apiVersion: v2
name: externalSecrets
description: Umbrella Chart for external-secrets
type: application
version: 0.2.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  - name: external-secrets
    repository: https://charts.external-secrets.io/
    version: 1.1.0  # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
