apiVersion: v2
name: loki
description: Umbrella Chart for loki
type: application
version: 0.3.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.46.0
  - name: promtail
    repository: https://grafana.github.io/helm-charts
    version: 6.17.1
