{{- if .Values.gatewaySystem }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: argo-slash-fix
  namespace: {{ .Values.gatewaySystem.namespace }}
spec:
  path:
    escapedSlashesAction: KeepUnchanged
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewaySystem.gateway.name }}
{{- end }}