apiVersion: v2
name: kube-prometheus-stack
description: Umbrella Chart for kube-prometheus-stack
type: application
version: 1.4.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 79.9.0
  - name: prometheus-blackbox-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: 11.5.0
