{{- if .Values.letsencrypt }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}
    solvers:
    {{- with .Values.clusterIssuer.solvers }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}