apiVersion: v2
name: vcluster
version: 1.0.0
description: This Chart deploys vcluster k3s by default.
#vcluster use default k3s
dependencies:
  - name: vcluster
    version: 0.30.4
    repository: https://charts.loft.sh
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
