apiVersion: v2
name: cert-manager
description: Umbrella Chart for cert-manager
type: application
version: 0.1.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  - name: cert-manager
    version: v1.19.1
    repository: https://charts.jetstack.io
