apiVersion: v2
name: argo-rollouts
description: Umbrella Chart for argo-rollouts
type: application
version: 0.3.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  # https://artifacthub.io/packages/helm/argo/argo-cd
  - name: argo-rollouts
    repository: https://argoproj.github.io/argo-helm
    version: 2.40.5
