apiVersion: v2
name: kyverno-policy-reporter
description: Umbrella Chart for kyverno-policy-reporter
type: application
version: 0.2.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  - name: policy-reporter
    repository: https://kyverno.github.io/policy-reporter
    version: 3.7.0
