apiVersion: v2
name: argocd
description: Umbrella Chart for argo-cd
type: application
version: 0.3.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  # https://artifacthub.io/packages/helm/argo/argo-cd
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.2.4
