apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module-03-blue-green
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  project: pe-gitops-prod
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: examples/module_03/podinfo-blue-green
    repoURL: git@github.com:InternalDeveloperPlatform/pe-gitops-course.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false