apiVersion: v2
name: kyverno
description: Umbrella Chart for kyverno
type: application
version: 0.1.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.4
  - name: kyverno
    repository: https://kyverno.github.io/kyverno
    version: 3.6.0
